// packages/react/src/TaktischesZeichen.tsx
import { SVGProps } from "react";
import {
  Container,
  Element,
  erzeugeTaktischesZeichen,
  TextNode,
  type TaktischesZeichen,
} from "taktische-zeichen-core";

export type Props = TaktischesZeichen & SVGProps<SVGSVGElement>;

export default function TaktischesZeichen({
  grundzeichen,
  fachaufgabe,
  organisation,
  einheit,
  verwaltungsstufe,
  funktion,
  symbol,
  text,
  name,
  typ,
  organisationName,
  farbe,
  skipFontRegistration,
  ...props
}: Props) {
  const { svg } = erzeugeTaktischesZeichen({
    grundzeichen,
    fachaufgabe,
    organisation,
    einheit,
    verwaltungsstufe,
    funktion,
    symbol,
    text,
    name,
    typ,
    organisationName,
    farbe,
    skipFontRegistration,
  });

  return render(svg, props);
}

function render(element: Element, additionalProps?: any) {
  const children =
    element instanceof Container
      ? element.children.map((child, key) => render(child, { key }))
      : element instanceof TextNode
        ? element.text
        : null;

  return (
    <element.name
      {...withCamelCaseKeys(element.attributes)}
      style={withCamelCaseKeys(element.styles)}
      {...additionalProps}
    >
      {children}
    </element.name>
  );
}

function withCamelCaseKeys(obj: Record<string, any>): Record<string, any> {
  return Object.entries(obj)
    .map(([key, value]) => [toCamelCase(key), value])
    .reduce((acc, [key, value]) => ({ ...acc, [key]: value }), {});
}

function toCamelCase(str: string): string {
  return str.replace(/^([A-Z])|[\s-_](\w)/g, function (_, p1, p2) {
    if (p2) return p2.toUpperCase();
    return p1.toLowerCase();
  });
}

// packages/vue/src/TaktischesZeichen.vue
<script setup lang="ts">
import { computed, h } from 'vue';
import {
  Container,
  Element,
  erzeugeTaktischesZeichen,
  TextNode,
  type TaktischesZeichen,
} from 'taktische-zeichen-core';

export interface Props extends TaktischesZeichen {}

const props = withDefaults(defineProps<Props>(), {});

const image = computed(() =>
  erzeugeTaktischesZeichen({
    grundzeichen: props.grundzeichen,
    fachaufgabe: props.fachaufgabe,
    organisation: props.organisation,
    einheit: props.einheit,
    verwaltungsstufe: props.verwaltungsstufe,
    funktion: props.funktion,
    symbol: props.symbol,
    text: props.text,
    name: props.name,
    typ: props.typ,
    organisationName: props.organisationName,
    farbe: props.farbe,
    skipFontRegistration: props.skipFontRegistration,
  })
);

function renderElement(element: Element, additionalAttrs?: Record<string, any>): any {
  const children =
    element instanceof Container
      ? element.children.map((child) => renderElement(child))
      : element instanceof TextNode
      ? element.text
      : null;

  return h(
    element.name,
    {
      ...element.attributes,
      style: element.styles,
      ...additionalAttrs,
    },
    children
  );
}
</script>

<template>
  <component :is="() => renderElement(image.svg, $attrs)" />
</template>
