// packages/react/src/TaktischesZeichen.tsx
import { SVGProps } from "react";
import {
  Container,
  Element,
  erzeugeTaktischesZeichen,
  TextNode,
  type TaktischesZeichen,
} from "taktische-zeichen-core";

export type Props = TaktischesZeichen & SVGProps<SVGSVGElement>;

export default function TaktischesZeichen({
  grundzeichen,
  fachaufgabe,
  organisation,
  einheit,
  verwaltungsstufe,
  funktion,
  symbol,
  text,
  name,
  typ,
  organisationName,
  farbe,
  skipFontRegistration,
  ...props
}: Props) {
  const { svg } = erzeugeTaktischesZeichen({
    grundzeichen,
    fachaufgabe,
    organisation,
    einheit,
    verwaltungsstufe,
    funktion,
    symbol,
    text,
    name,
    typ,
    organisationName,
    farbe,
    skipFontRegistration,
  });

  return render(svg, props);
}

function render(element: Element, additionalProps?: any) {
  const children =
    element instanceof Container
      ? element.children.map((child, key) => render(child, { key }))
      : element instanceof TextNode
        ? element.text
        : null;

  return (
    <element.name
      {...withCamelCaseKeys(element.attributes)}
      style={withCamelCaseKeys(element.styles)}
      {...additionalProps}
    >
      {children}
    </element.name>
  );
}

function withCamelCaseKeys(obj: Record<string, any>): Record<string, any> {
  return Object.entries(obj)
    .map(([key, value]) => [toCamelCase(key), value])
    .reduce((acc, [key, value]) => ({ ...acc, [key]: value }), {});
}

function toCamelCase(str: string): string {
  return str.replace(/^([A-Z])|[\s-_](\w)/g, function (_, p1, p2) {
    if (p2) return p2.toUpperCase();
    return p1.toLowerCase();
  });
}

// packages/web-component/src/TaktischesZeichen.ts
import {
  Container,
  Element,
  erzeugeTaktischesZeichen,
  TextNode,
  type TaktischesZeichen as TaktischesZeichenSpec,
} from "@taktische-zeichen/core";

export class TaktischesZeichen extends HTMLElement {
  constructor() {
    super();

    this.attachShadow({ mode: "open" });
    this.render();
  }

  attributeChangedCallback() {
    this.render();
  }

  private render() {
    const root = this.shadowRoot;
    if (!root) return;
    if (root.firstChild) root.removeChild(root.firstChild);

    const spec = this.spec;
    if (!spec) return;

    try {
      const { svg } = erzeugeTaktischesZeichen(spec);
      root.append(render(svg));
    } catch (error) {
      console.error(
        "Fehler bei der erzeugung des Taktischen Zeichens: " +
          JSON.stringify(spec),
        error,
      );
    }
  }

  private get spec(): TaktischesZeichenSpec | undefined {
    const grundzeichen = this.getAttribute("grundzeichen");
    const symbol = this.getAttribute("symbol");
    if (!grundzeichen && !symbol) return undefined;

    const fachaufgabe = this.getAttribute("fachaufgabe") || undefined;
    const organisation = this.getAttribute("organisation") || undefined;
    const einheit = this.getAttribute("einheit") || undefined;
    const verwaltungsstufe = this.getAttribute("verwaltungsstufe") || undefined;
    const funktion = this.getAttribute("funktion") || undefined;
    const text = this.getAttribute("text") || undefined;
    const name = this.getAttribute("name") || undefined;
    const typ = this.getAttribute("typ") || undefined;
    const organisationName = this.getAttribute("organisationName") || undefined;
    const farbe = this.getAttribute("farbe") || undefined;
    const skipFontRegistration =
      this.getAttribute("skipFontRegistration") === "true";

    return {
      grundzeichen,
      fachaufgabe,
      organisation,
      einheit,
      verwaltungsstufe,
      funktion,
      symbol,
      text,
      name,
      typ,
      organisationName,
      farbe,
      skipFontRegistration,
    } as TaktischesZeichenSpec;
  }

  static get observedAttributes() {
    return [
      "grundzeichen",
      "fachaufgabe",
      "organisation",
      "einheit",
      "verwaltungsstufe",
      "funktion",
      "symbol",
      "text",
      "name",
      "typ",
      "organisationName",
      "farbe",
      "skipFontRegistration",
    ];
  }
}

function render(element: Element) {
  const el = document.createElementNS(
    "http://www.w3.org/2000/svg",
    element.name,
  );

  Object.entries(element.attributes).forEach(([name, value]) => {
    el.setAttribute(name, value);
  });

  const style = Object.entries(element.styles)
    .map(([name, value]) => `${name}: ${value}`)
    .join(";");
  if (style) el.setAttribute("style", style);

  if (element instanceof Container) {
    element.children.forEach((child) => el.appendChild(render(child)));
  }

  if (element instanceof TextNode) {
    el.appendChild(document.createTextNode(element.text));
  }

  return el;
}
